In [21]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import scipy.integrate as scp
import numpy.linalg as nplin


In [32]:
# Cálculo de los autovalores por el método de Numerov

N = 10
V_0 = 4

x = np.eye(N,N,1)
y = np.eye(N,N,-1)
z = -2*np.eye(N,N)
w = V_0*np.eye(N,N)

w = x+y+z+w
w[:,0] = 0
w[:,N-1] = 0

print(w)

print('\n',nplin.eig(w)[0])

[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 2. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 2. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 2. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 2. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 2. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 2. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 2. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]

 [0.         0.         0.12061476 0.46791111 1.         3.87938524
 3.53208889 1.65270364 3.         2.34729636]
